### ISSUE TITLE
NoFlo GUI breaks installation

### ISSUE THREAD

**Issue by dbooth-boston** [rdf-pipeline/noflo-rdf-pipeline#53]

**Comment by catch-point** [comment]
The noflo-gui repository (and dependencies) does not use version numbering, which makes it very difficult to build previous versions and causes the build to be less stable then it would otherwise be (as the the dependencies are actively developed and change frequently). One particular place of instability is the in-browser noflo engine of noflo-gui, which is not used by the noflo-rdf-pipeline. To eliminate this component as a dependency a fork of noflo-gui is planned. This will remove the grunt dependency and with it all browser related built dependencies and replace them will already built version-controlled browser artifacts.

**Comment by dbooth-boston** [comment]
Fixed
